In [1]:
# Importing the libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
# Importing the dataset

In [4]:
dataset = pd.read_csv('Social_Network_Ads.csv')

In [5]:
dataset.head()

User ID  Gender   Age  EstimatedSalary  Purchased
0  15624510    Male  19.0          19000.0          0
1  15810944    Male  35.0          20000.0          0
2  15668575  Female  26.0          43000.0          0
3  15603246  Female  27.0          57000.0          0
4  15804002    Male  19.0          76000.0          0

In [6]:
X = dataset.iloc[:, [2, 3]]
y = dataset.iloc[:, 4]

In [7]:
# Splitting the dataset

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [10]:
# Feature Scaling

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
# Fitting Kernel SVM to the training set

In [14]:
from sklearn.svm import SVC

In [15]:
classifier = SVC(kernel='rbf', random_state=0)
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [16]:
# Predicting the Test set results

In [17]:
y_pred = classifier.predict(X_test)

In [18]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1], dtype=int64)

In [19]:
# Making the Confusion Matrix

In [20]:
from sklearn.metrics import confusion_matrix

In [21]:
cm = confusion_matrix(y_test, y_pred)

In [22]:
cm

array([[64,  4],
       [ 3, 29]], dtype=int64)

In [23]:
# Applying k-Fold Cross Validation

In [24]:
from sklearn.model_selection import cross_val_score

In [25]:
accuracies = cross_val_score(estimator=classifier, X=X_train, y=y_train, cv=10)

In [26]:
accuracies

array([0.8       , 0.96666667, 0.8       , 0.96666667, 0.86666667,
       0.86666667, 0.9       , 0.93333333, 1.        , 0.93333333])

In [27]:
accuracies.mean()

0.9033333333333333

In [28]:
accuracies.std()

0.06574360974438671

In [29]:
# Applying Grid Search to find the best model and the best parameters

In [37]:
from sklearn.model_selection import GridSearchCV

In [38]:
parameters = [{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
              {'C': [1, 10, 100, 1000], 'kernel': ['rbf'], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]}]

In [39]:
grid_search = GridSearchCV(estimator=classifier, param_grid=parameters, cv=10, n_jobs=-1)
grid_search = grid_search.fit(X_train, y_train)

In [40]:
best_accuracy = grid_search.best_score_

In [41]:
best_accuracy

0.9099999999999999

In [42]:
best_params = grid_search.best_params_

In [43]:
best_params

{'C': 1, 'gamma': 1.0, 'kernel': 'rbf'}