In [140]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

ERROR! Session/line number was not unique in database. History logging moved to new session 313


In [141]:
%matplotlib inline

In [142]:
dataset = pd.read_csv('50_Startups.csv')

In [143]:
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [144]:
X = np.array(dataset.iloc[:,:-1])
y = np.array(dataset.iloc[:,4])

In [145]:
from sklearn.model_selection import train_test_split

In [146]:
from sklearn.preprocessing import LabelEncoder

In [147]:
labelencoder_X = LabelEncoder()

In [148]:
X[:,3] = labelencoder_X.fit_transform(X[:,3])

In [149]:
from sklearn.compose import ColumnTransformer

In [150]:
from sklearn.preprocessing import OneHotEncoder

In [151]:
columntransformer_X = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder = 'passthrough')

In [152]:
X = np.array(columntransformer_X.fit_transform(X))

In [153]:
X = X[:,1:]

In [154]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [155]:
from sklearn.linear_model import LinearRegression

In [156]:
regressor = LinearRegression()

In [157]:
regressor.fit(X_train,y_train)

LinearRegression()

In [158]:
y_pred = regressor.predict(X_test)

In [159]:
y_pred

array([103015.20159795, 132582.27760817, 132447.73845176,  71976.09851257,
       178537.48221058, 116161.24230165,  67851.69209675,  98791.73374686,
       113969.43533013, 167921.06569553])

In [160]:
import statsmodels.formula.api as sm

In [161]:
X = np.append(arr=np.ones((50,1)).astype(int), values=X, axis=1)

In [162]:
X

array([[1, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [1, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [1, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [1, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [1, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [1, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [1, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [1, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [1, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [1, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [1, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [1, 0.0, 1.0, 94657.16, 145077.58, 282574.31],
       [1, 1.0, 0.0, 9

In [163]:
#X_opt = X[:,[0,1,2,3,4,5]]
#regressor_ols = sm.ols(y,X_opt).fit()

In [164]:
X_opt = X[:,[0,1,2,3,4,5]]
regressor_ols = sm.ols(y,X_opt).fit()

In [165]:
import statsmodels.api as smf

In [166]:
#regressor_ols = smf.Logit(endog=y,exog=X_opt).fit()

In [ ]:
regressor_ols = sm.ols(formula= 'X_opt[:,5] ~ X_opt[:,:5]', data = X_opt).fit()

In [170]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[103015.2  103282.38]
 [132582.28 144259.4 ]
 [132447.74 146121.95]
 [ 71976.1   77798.83]
 [178537.48 191050.39]
 [116161.24 105008.31]
 [ 67851.69  81229.06]
 [ 98791.73  97483.56]
 [113969.44 110352.25]
 [167921.07 166187.94]]


In [ ]:
X_opt = X[:,[0,1,2,3,4,5]]
regressor_ols = sm.ols(endog=y,exog=X_opt).fit()
regressor_ols.summary()
X_opt = X[:,[0,1,3,4,5]]
regressor_ols = sm.ols(endog=y,exog=X_opt).fit()
regressor_ols.summary()
X_opt = X[:,[0,1,3,5]]
regressor_ols = sm.ols(endog=y,exog=X_opt).fit()
regressor_ols.summary()
X_opt = X[:,[0,3,5]]
regressor_ols = sm.ols(endog=y,exog=X_opt).fit()
regressor_ols.summary()
X_opt = X[:,[0,3,]]
regressor_ols = sm.ols(endog=y,exog=X_opt).fit()
regressor_ols.summary()